import { MatAutocompleteModule,
         MatBadgeModule,
         MatBottomSheetModule,
         MatButtonModule,
         MatButtonToggleModule,
         MatCardModule,
         MatCheckboxModule,
         MatChipsModule,
         MatDatepickerModule,
         MatDialogModule,
         MatDividerModule,
         MatExpansionModule,
         MatGridListModule,
         MatIconModule,
         MatInputModule,
         MatListModule,
         MatMenuModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSelectModule,
         MatSidenavModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSnackBarModule,
         MatSortModule,
         MatStepperModule,
         MatTableModule,
         MatTabsModule,
         MatTooltipModule,
         MatTreeModule,
         MatFormFieldModule,} from '@angular/material';

import {MatToolbarModule} from '@angular/material/toolbar';    

import { AngularBootstrapModule } from './angular-bootstrap';


import { NgModule } from '@angular/core';

@NgModule({
  imports: [ MatAutocompleteModule,
             MatBadgeModule,
             MatBottomSheetModule,
             MatButtonModule,
             MatButtonToggleModule,
             MatCardModule,
             MatCheckboxModule,
             MatChipsModule,
             MatDatepickerModule,
             MatDialogModule,
             MatDividerModule,
             MatExpansionModule,
             MatGridListModule,
             MatIconModule,
             MatInputModule,
             MatListModule,
             MatMenuModule,
             MatNativeDateModule,
             MatPaginatorModule,
             MatProgressBarModule,
             MatProgressSpinnerModule,
             MatRadioModule,
             MatRippleModule,
             MatSelectModule,
             MatSidenavModule,
             MatSliderModule,
             MatSlideToggleModule,
             MatSnackBarModule,
             MatSortModule,
             MatStepperModule,
             MatTableModule,
             MatTabsModule,
             MatToolbarModule,
             MatTooltipModule,
             MatFormFieldModule,
            //  AngularBootstrapModule,
             MatTreeModule, ],
  exports: [MatAutocompleteModule,
            MatBadgeModule,
            MatBottomSheetModule,
            MatButtonModule,
            MatButtonToggleModule,
            MatCardModule,
            MatCheckboxModule,
            MatChipsModule,
            MatDatepickerModule,
            MatDialogModule,
            MatDividerModule,
            MatExpansionModule,
            MatGridListModule,
            MatIconModule,
            MatInputModule,
            MatListModule,
            MatMenuModule,
            MatNativeDateModule,
            MatPaginatorModule,
            MatProgressBarModule,
            MatProgressSpinnerModule,
            MatRadioModule,
            MatRippleModule,
            MatSelectModule,
            MatSidenavModule,
            MatSliderModule,
            MatSlideToggleModule,
            MatSnackBarModule,
            MatSortModule,
            MatStepperModule,
            MatTableModule,
            MatTabsModule,
            MatToolbarModule,
            MatTooltipModule,
            MatFormFieldModule,
            // AngularBootstrapModule,
            MatTreeModule,],
})
export class MaterialModule { }